export const theme = {
    colors: {
        primary: '#2563EB',
        primaryLight: '#EFF6FF',
        primaryDark: '#1D4ED8',
        background: '#F8FAFC',
        card: '#FFFFFF',
        text: '#1E293B',
        textSecondary: '#64748B',
        textLight: '#94A3B8',
        border: '#E2E8F0',
        success: '#10B981',
        error: '#EF4444',
        warning: '#F59E0B',
        booked: '#F1F5F9',
        bookedText: '#94A3B8',
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
    },
    radius: {
        sm: 8,
        md: 12,
        lg: 16,
        xl: 24,
    },
    shadow: {
        shadowColor: '#1E293B',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    fontSize: {
        xs: 11,
        sm: 13,
        md: 15,
        lg: 17,
        xl: 20,
        xxl: 24,
        xxxl: 28,
    },
};